### ISSUE TITLE
Правописни корекции

### ISSUE THREAD

**Issue by neterbg** [OpenFest/clarion#24]
В текста на "зов за лектори":
- "категории до" трябва да е "категории, до";
- "неща,които" трябва да е "неща, които";
- "презентациите ви" трябва да е "презентациите Ви", или "предложенията Ви" трябва да е "предложенията ви" (зависи дали се иска запазване на учтивата форма, като правилото за главната буква не се интересува дали се използва в единствено, или в множествено число).

**Comment by krokodilerian** [comment]
"неща, които" е оправено.

**Comment by krokodilerian** [comment]
Останалите неща също са оправени, само трябва да се redeploy-не.
