### ISSUE TITLE
Избор на продължителност на лекция/уъркшоп

### ISSUE THREAD

**Issue by neterbg** [OpenFest/clarion#25]
Що се касае до лекциите, чудя се имали ли сме лектор, който може с чиста съвест да избере за продължителност на лекцията си 40 или 45 минути, камо ли стойност между тях. Още повече, че при всички стойности в този диапазон лекцията му ще си заеме един цял слот. Виждам смисъл в избора на продължителност, ако му се дава възможност да укаже лекция с продължителност цял слот, половин слот (при което евентуално да се комбинира с друга такава лекция, за да заемат общо цял слот) или два слота (ако въобще се очаква да се появи лекция с такава продължителност, която няма да приспи публиката). Но и да си остане текущият тесен избор, намирам за излишно (дори малко вредно) полето да е със свободно въвеждане на продължителност (текущо дори и с възможност за въвеждане на отрицателни стойности) - падащо меню или радио бутони с всички валидни стойности би било по-удобно и недвусмислено за избор от лектора, което допълнително може да спести или скъси обяснителния текст под това поле. Всичко това важи за полетата и в двата вида предложения - лекция и уъркшоп.

**Comment by ignisf** [comment]
Обърни се към кор екипа
